/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ArchitectureRouteImport } from './routes/architecture'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as OpenapiRouteImport } from './routes/openapi'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TelemetryRouteImport } from './routes/telemetry'
import { Route as VehiclesIndexRouteImport } from './routes/vehicles.index'
import { Route as VehiclesIdRouteImport } from './routes/vehicles.$id'
import { Route as ApiPublicAlertsRouteImport } from './routes/api/public/alerts'
import { Route as ApiPublicAnalyticsRouteImport } from './routes/api/public/analytics'
import { Route as ApiPublicDashboardRouteImport } from './routes/api/public/dashboard'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as ApiPublicMaintenanceRouteImport } from './routes/api/public/maintenance'
import { Route as ApiPublicOpenapiDotjsonRouteImport } from './routes/api/public/openapi[.]json'
import { Route as ApiPublicTelemetryRouteImport } from './routes/api/public/telemetry'
import { Route as ApiPublicVehiclesRouteImport } from './routes/api/public/vehicles'
import { Route as ApiPublicSimulateTickRouteImport } from './routes/api/public/simulate.tick'
import { Route as ApiPublicVehiclesIdRouteImport } from './routes/api/public/vehicles.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ArchitectureRoute = ArchitectureRouteImport.update({
  id: '/architecture',
  path: '/architecture',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenapiRoute = OpenapiRouteImport.update({
  id: '/openapi',
  path: '/openapi',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TelemetryRoute = TelemetryRouteImport.update({
  id: '/telemetry',
  path: '/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIndexRoute = VehiclesIndexRouteImport.update({
  id: '/vehicles/',
  path: '/vehicles/',
  getParentRoute: () => rootRouteImport,
} as any)
const VehiclesIdRoute = VehiclesIdRouteImport.update({
  id: '/vehicles/$id',
  path: '/vehicles/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAlertsRoute = ApiPublicAlertsRouteImport.update({
  id: '/api/public/alerts',
  path: '/api/public/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAnalyticsRoute = ApiPublicAnalyticsRouteImport.update({
  id: '/api/public/analytics',
  path: '/api/public/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicDashboardRoute = ApiPublicDashboardRouteImport.update({
  id: '/api/public/dashboard',
  path: '/api/public/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMaintenanceRoute = ApiPublicMaintenanceRouteImport.update({
  id: '/api/public/maintenance',
  path: '/api/public/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenapiDotjsonRoute = ApiPublicOpenapiDotjsonRouteImport.update({
  id: '/api/public/openapi.json',
  path: '/api/public/openapi.json',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelemetryRoute = ApiPublicTelemetryRouteImport.update({
  id: '/api/public/telemetry',
  path: '/api/public/telemetry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVehiclesRoute = ApiPublicVehiclesRouteImport.update({
  id: '/api/public/vehicles',
  path: '/api/public/vehicles',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSimulateTickRoute = ApiPublicSimulateTickRouteImport.update({
  id: '/api/public/simulate/tick',
  path: '/api/public/simulate/tick',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicVehiclesIdRoute = ApiPublicVehiclesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicVehiclesRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/maintenance': typeof MaintenanceRoute
  '/openapi': typeof OpenapiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemetry': typeof TelemetryRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/vehicles': typeof ApiPublicVehiclesRouteWithChildren
  '/api/public/simulate/tick': typeof ApiPublicSimulateTickRoute
  '/api/public/vehicles/$id': typeof ApiPublicVehiclesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/maintenance': typeof MaintenanceRoute
  '/openapi': typeof OpenapiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemetry': typeof TelemetryRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles': typeof VehiclesIndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/vehicles': typeof ApiPublicVehiclesRouteWithChildren
  '/api/public/simulate/tick': typeof ApiPublicSimulateTickRoute
  '/api/public/vehicles/$id': typeof ApiPublicVehiclesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/architecture': typeof ArchitectureRoute
  '/maintenance': typeof MaintenanceRoute
  '/openapi': typeof OpenapiRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/telemetry': typeof TelemetryRoute
  '/vehicles/$id': typeof VehiclesIdRoute
  '/vehicles/': typeof VehiclesIndexRoute
  '/api/public/alerts': typeof ApiPublicAlertsRoute
  '/api/public/analytics': typeof ApiPublicAnalyticsRoute
  '/api/public/dashboard': typeof ApiPublicDashboardRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/maintenance': typeof ApiPublicMaintenanceRoute
  '/api/public/openapi.json': typeof ApiPublicOpenapiDotjsonRoute
  '/api/public/telemetry': typeof ApiPublicTelemetryRoute
  '/api/public/vehicles': typeof ApiPublicVehiclesRouteWithChildren
  '/api/public/simulate/tick': typeof ApiPublicSimulateTickRoute
  '/api/public/vehicles/$id': typeof ApiPublicVehiclesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/maintenance'
    | '/openapi'
    | '/sitemap.xml'
    | '/telemetry'
    | '/vehicles/$id'
    | '/vehicles/'
    | '/api/public/alerts'
    | '/api/public/analytics'
    | '/api/public/dashboard'
    | '/api/public/health'
    | '/api/public/maintenance'
    | '/api/public/openapi.json'
    | '/api/public/telemetry'
    | '/api/public/vehicles'
    | '/api/public/simulate/tick'
    | '/api/public/vehicles/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/maintenance'
    | '/openapi'
    | '/sitemap.xml'
    | '/telemetry'
    | '/vehicles/$id'
    | '/vehicles'
    | '/api/public/alerts'
    | '/api/public/analytics'
    | '/api/public/dashboard'
    | '/api/public/health'
    | '/api/public/maintenance'
    | '/api/public/openapi.json'
    | '/api/public/telemetry'
    | '/api/public/vehicles'
    | '/api/public/simulate/tick'
    | '/api/public/vehicles/$id'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/architecture'
    | '/maintenance'
    | '/openapi'
    | '/sitemap.xml'
    | '/telemetry'
    | '/vehicles/$id'
    | '/vehicles/'
    | '/api/public/alerts'
    | '/api/public/analytics'
    | '/api/public/dashboard'
    | '/api/public/health'
    | '/api/public/maintenance'
    | '/api/public/openapi.json'
    | '/api/public/telemetry'
    | '/api/public/vehicles'
    | '/api/public/simulate/tick'
    | '/api/public/vehicles/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  ArchitectureRoute: typeof ArchitectureRoute
  MaintenanceRoute: typeof MaintenanceRoute
  OpenapiRoute: typeof OpenapiRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TelemetryRoute: typeof TelemetryRoute
  VehiclesIdRoute: typeof VehiclesIdRoute
  VehiclesIndexRoute: typeof VehiclesIndexRoute
  ApiPublicAlertsRoute: typeof ApiPublicAlertsRoute
  ApiPublicAnalyticsRoute: typeof ApiPublicAnalyticsRoute
  ApiPublicDashboardRoute: typeof ApiPublicDashboardRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicMaintenanceRoute: typeof ApiPublicMaintenanceRoute
  ApiPublicOpenapiDotjsonRoute: typeof ApiPublicOpenapiDotjsonRoute
  ApiPublicTelemetryRoute: typeof ApiPublicTelemetryRoute
  ApiPublicVehiclesRoute: typeof ApiPublicVehiclesRouteWithChildren
  ApiPublicSimulateTickRoute: typeof ApiPublicSimulateTickRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/architecture': {
      id: '/architecture'
      path: '/architecture'
      fullPath: '/architecture'
      preLoaderRoute: typeof ArchitectureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/openapi': {
      id: '/openapi'
      path: '/openapi'
      fullPath: '/openapi'
      preLoaderRoute: typeof OpenapiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/telemetry': {
      id: '/telemetry'
      path: '/telemetry'
      fullPath: '/telemetry'
      preLoaderRoute: typeof TelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/': {
      id: '/vehicles/'
      path: '/vehicles'
      fullPath: '/vehicles/'
      preLoaderRoute: typeof VehiclesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vehicles/$id': {
      id: '/vehicles/$id'
      path: '/vehicles/$id'
      fullPath: '/vehicles/$id'
      preLoaderRoute: typeof VehiclesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/alerts': {
      id: '/api/public/alerts'
      path: '/api/public/alerts'
      fullPath: '/api/public/alerts'
      preLoaderRoute: typeof ApiPublicAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/analytics': {
      id: '/api/public/analytics'
      path: '/api/public/analytics'
      fullPath: '/api/public/analytics'
      preLoaderRoute: typeof ApiPublicAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/dashboard': {
      id: '/api/public/dashboard'
      path: '/api/public/dashboard'
      fullPath: '/api/public/dashboard'
      preLoaderRoute: typeof ApiPublicDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/maintenance': {
      id: '/api/public/maintenance'
      path: '/api/public/maintenance'
      fullPath: '/api/public/maintenance'
      preLoaderRoute: typeof ApiPublicMaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openapi.json': {
      id: '/api/public/openapi.json'
      path: '/api/public/openapi.json'
      fullPath: '/api/public/openapi.json'
      preLoaderRoute: typeof ApiPublicOpenapiDotjsonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telemetry': {
      id: '/api/public/telemetry'
      path: '/api/public/telemetry'
      fullPath: '/api/public/telemetry'
      preLoaderRoute: typeof ApiPublicTelemetryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicles': {
      id: '/api/public/vehicles'
      path: '/api/public/vehicles'
      fullPath: '/api/public/vehicles'
      preLoaderRoute: typeof ApiPublicVehiclesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/simulate/tick': {
      id: '/api/public/simulate/tick'
      path: '/api/public/simulate/tick'
      fullPath: '/api/public/simulate/tick'
      preLoaderRoute: typeof ApiPublicSimulateTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/vehicles/$id': {
      id: '/api/public/vehicles/$id'
      path: '/$id'
      fullPath: '/api/public/vehicles/$id'
      preLoaderRoute: typeof ApiPublicVehiclesIdRouteImport
      parentRoute: typeof ApiPublicVehiclesRoute
    }
  }
}

interface ApiPublicVehiclesRouteChildren {
  ApiPublicVehiclesIdRoute: typeof ApiPublicVehiclesIdRoute
}

const ApiPublicVehiclesRouteChildren: ApiPublicVehiclesRouteChildren = {
  ApiPublicVehiclesIdRoute: ApiPublicVehiclesIdRoute,
}

const ApiPublicVehiclesRouteWithChildren =
  ApiPublicVehiclesRoute._addFileChildren(ApiPublicVehiclesRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  ArchitectureRoute: ArchitectureRoute,
  MaintenanceRoute: MaintenanceRoute,
  OpenapiRoute: OpenapiRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TelemetryRoute: TelemetryRoute,
  VehiclesIdRoute: VehiclesIdRoute,
  VehiclesIndexRoute: VehiclesIndexRoute,
  ApiPublicAlertsRoute: ApiPublicAlertsRoute,
  ApiPublicAnalyticsRoute: ApiPublicAnalyticsRoute,
  ApiPublicDashboardRoute: ApiPublicDashboardRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicMaintenanceRoute: ApiPublicMaintenanceRoute,
  ApiPublicOpenapiDotjsonRoute: ApiPublicOpenapiDotjsonRoute,
  ApiPublicTelemetryRoute: ApiPublicTelemetryRoute,
  ApiPublicVehiclesRoute: ApiPublicVehiclesRouteWithChildren,
  ApiPublicSimulateTickRoute: ApiPublicSimulateTickRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
